# 서버 포트 : 0(랜덤 포트 지정)
server:
  port: 0

# 스프링 서버 이름
spring:
  application:
    name: user-service
    # rabbitmq 정보
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
# Config Microservice 와 연동해서 설정정보 파일을 불러온다.
  # Config Microservice 세팅
  cloud:
    config:
      name: config-service
  # Config File 세팅
  config:
    import: optional:configserver:http://localhost:8888
    name: user-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # 인스턴스 아이디 지정
  client:
    register-with-eureka: true  # EUREKA Registry 에 등록 여부
    fetch-registry: true        # EUREKA Registry 에 등록되어있는 정보를 가져올지 여부
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice: DEBUG

# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
