server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Volumes/T7/Repository/local-config-repo
          uri: https://github.com/CokeLee777/spring-cloud-config
          default-label: master