server:
  port: 8761

spring:
  application:
    name: discoveryservice
  config:
    import:
      - classpath:/bootstrap.yml


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false